//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Football_Shop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customers
    {
        public int id_customer { get; set; }
        public string password { get; set; }
        public string Name { get; set; }
        public string phone_number { get; set; }
        public string Email { get; set; }
    }
}
