//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Football_Shop.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Football_ShopEntities : DbContext
    {
        public Football_ShopEntities()
            : base("name=Football_ShopEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Ball> Balls { get; set; }
        public virtual DbSet<Boot> Boots { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<OrderInShop> OrderInShops { get; set; }
        public virtual DbSet<PurchaseBall> PurchaseBalls { get; set; }
        public virtual DbSet<PurchaseBoot> PurchaseBoots { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
