//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Football_Shop.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Football_ShopEntities : DbContext
    {
        public Football_ShopEntities()
            : base("name=Football_ShopEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Balls> Balls { get; set; }
        public virtual DbSet<Boots> Boots { get; set; }
        public virtual DbSet<Customer> Customer { get; set; }
        public virtual DbSet<OrderInShop> OrderInShop { get; set; }
        public virtual DbSet<PurchaseBalls> PurchaseBalls { get; set; }
        public virtual DbSet<PurchaseBoots> PurchaseBoots { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
