//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Football_Shop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseBoots
    {
        public int id_purchase { get; set; }
        public Nullable<int> id_product { get; set; }
        public Nullable<int> price { get; set; }
        public Nullable<int> count_the_product { get; set; }
        public Nullable<System.DateTime> date_of_change { get; set; }
    
        public virtual Boots Boots { get; set; }
    }
}
